language: node_js

branches:
  only:
   - master

cache:
  directories:
    - node_modules

env:
  global:
    # algolia api
    - secure: "ntU6zdkllBVbo7mzBcKFJaLn3OmwHTx/cboX15YkHjDPHhzYkUjz5+I8jqrPsp0CqO6HLE9SYJyPHOLwXVPiyi4HzfQmUuBhDrFWdx05yoxTSxUDPmRmLgnwIndLYkTE/lJhJk8EVZ3PCIHOuBdGo6VBIDroGyuRp611IGWj5Pr8F63qd7uE51/GAtyB7BSttB7F8I2mTggsl4zv28tqyIeHFuq4XTdKFNmncZ4a9nZNPVEpKLaZAg1Q8+G+uP86Cr9486ia64PVyilHievwcSAmATAyolaUGpG8y0eRE+PqjUHFMbNF83u9A9qVUlUr72TZiR1+2dPYo3nrwFWSz4xQ7gv5023DvwHv7PU8onfKLFQDH1KOnvTLNtR1wjksc/ieVosHVh7QQSzu6COMcBJjy6+azJwLSKMqQ3Jt2cvcg61aD28uQ+/bNqXqFPRNYrdvQDDhmqMz6z1PvbZU+jdI9hpGoi5jX0bR9Z96m9hJMrpSbReZNMBs4alVhuydRnmQZeE55liPDo79JaeyCFLO5L7Vx1BTVlhif4WTOaf3UJFeo4oRZHIlu1gNEHBD3bYyVIHgN1U0Cb5U+/K0mbfMF5rz2pcAYmr0920cfAvLrOYiWu5RXboQuREmrvDB7lJfDdli4mtcXfxRieAupMMlpWkD7vGT/ZsH8vqruGk="
    # google api
    - secure: "HXiozVjqCl/b9Ekahhyuco4Xb50eAKZPX50oymo5/Q9UNGXeiB2xGFppjZmmjzA/U4cNPl2hAIe0Ia25Sqw19lM9UrMceiC1o7XVZa5BY4dmUv4iJoKmiYUW+Cs6mr4UsUiPRdSBMmHGZBcyQeF1WkifQJnnJpq4hSpbOQnLAwAwZo1eL8NYEhGse6ox3nJWgaJzcQ0GJ1LmOayJrSf/4IBEdd8NwnTH6z8lD1AAqRfq4YAKMyTn6rUFBj2gIA6Yt4zHQyCXKde4UZ6ovy+Dy5EOHfGOxpsX/EgNsZWrt+edoL93hClcGl+Eb4H36V/+KQPedS/saVlYRERfbJH9lw303sh8g4Ci7JOFaD7YyNDuXVVOweRJMTGTMyXUMq8whuNKx51Ulc/UGePlVHSuf/5QMBYkYibVNey5iPg7EutrfWVkhrM05P+4j7kmBofqyMqrWO6ngZkASsAhkveX0TctxqcIU3h0wOpzwOvyTroaJlYPi6zo9Hg6PhQd9s7Ws/5V9naArkvFIG4nWMv3ofSIHejRgzVyMPZL+Mob93R6M7TksDZCzCbiOdZzUoaeOyS5+CIzSbuC6QkjZg45zPUcoVY0Woa3Ab/G1l2fKifCPa8cB06hWl2P35Xu+4hWKXgxr72+O5L6zJCTLEg3O+XGXTS44QA+PI77V9hWaSo="
    # goodread sapi
    - secure: "l4uOGPKO9eJ0379bwrWjRqCS9NI51kKRlNt/Wj3oqYDesikLjO8zz9UnrECxGFzr/Z8G5Qvs53w21RVW1/FQZb4/lT8/8JsUMLSu65DY7dwd8drQNqxAfkC3zY3OkLDyBxMi0StEas+ZESQnMdq6oyt5LDMGRMOas4SwkjimKGyWX7fTTK7a/5m63OcDuIGmxtdLkalX9Og92xZocbtYrry17DBzHgIaMNz51z/5rXmRrZwVeTa0jOQATHyD3i+LT3iOWA1Tj0nqbRd2bv9nLFOwF0CLw5JilKEBP3rmJRWJx9LurZl/XXzdcOOMvCUBacoiKpjB1VnoNTqpxUt4pbGPbhMpMVbd0BdvqUFOUdn5d9Gw05fviNxqk5AOcfwrxyYSyJndnPQ7fg0iZB6KK9XlLC0C9j2MHA93Xs6ms+6XyVlgy1j/oNbT6WG/RpNmjD8uzhKZuG2C+xkqe0X7TjYosyn12Q6SLls7rOQ4Q1ZwGpjai1YnnSbeY3s+mThVuZHz6nldT472psWofrooWCrsJjKbbw0jeAYMEEo/X9lOmiy1lEI+76G2GnWSPNKz++OkmgV2FOB4vX6kz4ONIFj5N+3ayfcKF/ILUKFD+DDjOpcVRUUNhHiwxN+u6GkUT7DyqdptEgI87KqdQ7+bhqDajkfxpRMEW6WT/u+ddCg="
  matrix:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/googleServiceAccount.json ALGOLIA_APP_ID=DR90AOGGE9 ALGOLIA_INDEX_NAME=prod_BOOKS

before_install:
  - openssl aes-256-cbc -K $encrypted_ae0a0ec024c5_key -iv $encrypted_ae0a0ec024c5_iv -in googleServiceAccount.json.enc -out googleServiceAccount.json -d
  - npm i yarn -g 

script:
  - yarn index